config/routes.rb
Rails.application.routes.draw do

  resources :merma_lotes

  resources :merma_vencimientos

  resources :detalle_entrega_insumos

  resources :detalles_basicos

  resources :create_detalles_basicos

  resources :proveedors

  get 'recepcion_materiales/insumos'

  get 'recepcion_materiales/ingredientes'

  resources :merma_ingredientes

  resources :merma_insumos

  match "/404", :to => "errors#not_found", via: 'get'
  match "/422", :to => "errors#unacceptable", via: 'get'
  match "/500", :to => "errors#internal_error", via: 'get'
  match "/acceso_denegado", :to => "errors#acceso_denegado", via: 'get'
  
  post 'users/crear' => 'user#crear'
  get '/usuarios' => 'user#index'

  get 'preparar' => 'preparar#index'
  get 'preparar_pruebas' => 'preparar#pruebas'
  get 'preparar/cambiar_estado/:id_venta/:tipo_producto/:id_producto' => 'preparar#cambiar_estado'

  resources :lotes

  resources :insumos

  resources :merma_materials and resources :merma_material

  get 'mermas/ingresar_merma'

  resources :detalles

  get 'venta/historial' => 'venta#historial'
  get 'venta/:id/cambiar_estado/:estado_nuevo' => 'venta#cambiar_estado'
  resources :venta do
    get 'index_path'
  end

  resources :ingredientes and resources :ingrediente

  devise_for :users
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/users/sign_up' => 'devise/registrations#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  resources :users, :controller => "user"

  root 'basicos#index'
  resources :alerta_obsolescencia

  resources :compuestos

  resources :basicos

  post ':controller(/:action(/:id(.:format)))'
  get ':controller(/:action(/:id(.:format)))'

end

app/models/venta.rb
class Venta < ActiveRecord::Base
	belongs_to :user, foreign_key: "vendedor_id"
	has_many :detalle
	has_many :basico,    -> { distinct }, :through => :detalle
	has_many :compuesto, -> { distinct }, :through => :detalle

	accepts_nested_attributes_for :basico
	accepts_nested_attributes_for :compuesto
	accepts_nested_attributes_for :detalle

	CANCELADA  = 0
	EMITIDA    = 1
	PREPARANDO = 2
	FINALIZADA = 3
	ENTREGADA  = 4

	def self.estados
		{
			'CANCELADA'    => CANCELADA,
			'EMITIDA'      => EMITIDA,
			'PREPARANDO'   => PREPARANDO,
			'FINALIZADA'   => FINALIZADA,
			'ENTREGADA'    => ENTREGADA,
		}
	end
end

app/controllers/venta_controller.rb
class VentaController < ApplicationController
  check_authorization
  before_filter :authenticate_user!#, :except => [:index, :show]
  load_and_authorize_resource param_method: :compuesto_params
  before_action :set_venta, only: [:show, :edit, :update, :destroy, :cambiar_estado]

  # GET /venta
  # GET /venta.json
  def index
    @venta = Venta.order(fecha_hora: :desc).where('date(fecha_hora) = ?', Time.now.strftime("%Y-%m-%d"))
  end

  def historial
    @venta = Venta.order(fecha_hora: :desc).where('date(fecha_hora) = ?', Time.now.strftime("%Y-%m-%d"))
  end

  # GET /venta/1
  # GET /venta/1.json
  def show
  end

  # GET /venta/new
  def new
    @venta = Venta.new
    @venta.numero_de_caja = 1
    @venta.estado_venta = Venta.estados['PREPARANDO']
    @venta.comentario_perdida = ''
    
    basicos = Basico.where(en_venta: true)
    compuestos = Compuesto.where(en_venta: true)

    basicos.each do | basico |
      basico.tipo = 'basico'
    end

    compuestos.each do | compuesto |
      compuesto.tipo = 'compuesto'
    end

    @diferencia_basicos = basicos + compuestos
  end

  # GET /venta/1/edit
  def edit
  end

  # POST /venta
  # POST /venta.json
  def create
    @venta = Venta.new(venta_params)
    
    respond_to do |format|
      @venta.vendedor_id = current_user.id
      @venta.fecha_hora = Time.now
      @venta.numero_de_caja = 1
      @venta.estado_venta = Venta::PREPARANDO

      ##### Agregar Basicos #####
      basicos = Array.new
      if !params[:venta][:basico].nil?
          params[:venta][:basico].each do | basico |

          #id = basico['id'].slice('basico_').to_s.slice('compuesto_').to_s
          #basico['id']['basico_'] = ''
          id = basico['id'].sub('basico_', '')
          id =        id.sub('compuesto_', '')
          tipo = basico['id'].sub('_'+id, '')
          basicos.push(:id => id, :cantidad => basico['cantidad'], :comentario => basico['comentario'], :tipo => tipo)
          #basicos.push(:id => basico['id'], :comentario => basico['comentario'])
      end
    end

    i = 0
    @venta.basico = Array.new
    @venta.compuesto = Array.new
    @venta.detalle = Array.new

    @venta.precio_total = 0;
    
    productos_validos = true

    basicos.each do | basico |
        if basico[:tipo] == 'basico'
            if Basico.exists?(:id => basico[:id])
                basico_nuevo = Basico.find(basico[:id])
                @venta.basico.push basico_nuevo
            else
                productos_validos = false
                @venta.errors.add :general, "Ingreso un producto inválido, ingréselos nuevamente porfavor."
                break
            end
        elsif basico[:tipo] == 'compuesto'
            if Compuesto.exists?(:id => basico[:id])
                basico_nuevo = Compuesto.find(basico[:id])
                @venta.compuesto.push basico_nuevo
            else
                productos_validos = false
                @venta.errors.add :general, "Ingreso un producto inválido, ingréselos nuevamente porfavor."
                break
            end
        else
            productos_validos = false
            @venta.errors.add :general, "Ingreso un producto inválido, ingréselos nuevamente porfavor."
            break
        end

        if productos_validos
            @venta.detalle[i].cantidad = basico[:cantidad]
            @venta.detalle[i].comentario = basico[:comentario]
            @venta.detalle[i].precio = basico_nuevo.precio.to_i * basico[:cantidad].to_i
            @venta.detalle[i].estado = Venta::PREPARANDO

            @venta.precio_total += basico_nuevo.precio.to_i * basico[:cantidad].to_i
        end
        i = i + 1
    end
    
    basicos = Basico.where(en_venta: true)
    compuestos = Compuesto.where(en_venta: true)

    basicos.each do | basico |
        basico.tipo = 'basico'
    end

    compuestos.each do | compuesto |
        compuesto.tipo = 'compuesto'
    end

    if productos_validos
        @diferencia_basicos = (basicos - @venta.basico ) + (compuestos  - @venta.compuesto)
        #@diferencia_basicos = @venta.basico

        tiene_productos = @venta.basico.any? and @venta.compuesto.any?
        if !tiene_productos
            @venta.errors.add :general, "Debe agregar a lo menos un producto."
        end
    else
        @venta.basico = Array.new
        @venta.compuesto = Array.new

        @diferencia_basicos = basicos + compuestos
    end

    if productos_validos and tiene_productos and @venta.valid?
        # descontamos el stock
        if @venta.detalle.any?
            i = 0
            @venta.detalle.each do | detalle |
                if !detalle.basico_id.nil?
                    basico = Basico.find(detalle.basico_id)
                    
                    j = 0
                        basico.ingredientes.each do | ingrediente |
                            detalle_basico = DetallesBasico.where(:basico_id => detalle.basico_id, :ingrediente_id => ingrediente.id)

                            if !detalle_basico.nil?
                                nueva_cantidad = ingrediente.stock_actual - detalle.cantidad * detalle_basico[0].cantidad
                                ingrediente.stock_actual = nueva_cantidad
                            end
                            ingrediente.save
                            #raise (detalle.cantidad * detalle_basico[0].cantidad).to_s
                            j = j + 1
                        end

                    i = i + 1
                elsif !detalle.compuesto_id.nil?
                    compuesto = Compuesto.find(detalle.compuesto_id)
                    
                    compuesto.basico.each do | basico |

                        j = 0
                        basico.ingredientes.each do | ingrediente |
                            detalle_basico = DetallesBasico.where(:basico_id => basico.id, :ingrediente_id => ingrediente.id)

                            if !detalle_basico.nil?
                                nueva_cantidad = ingrediente.stock_actual - detalle.cantidad * detalle_basico[0].cantidad
                                ingrediente.stock_actual = nueva_cantidad
                            end
                            ingrediente.save
                            #raise (detalle.cantidad * detalle_basico[0].cantidad).to_s
                            j = j + 1
                        end
                    
                    end

                    i = i + 1
                end
            end
        end
        # / descontamos el stock
        @venta.save
        #format.html { redirect_to @venta, notice: 'Venta añadida correctamente.' }
        format.html { redirect_to '/venta', notice: 'Venta añadida correctamente.' }
        format.json { render :show, status: :created, location: @venta }
    else
        format.html { render :new }
        format.json { render json: @venta.errors, status: :unprocessable_entity }
    end
end
end

  # PATCH/PUT /venta/1
  # PATCH/PUT /venta/1.json
  #def update
    #respond_to do |format|
      #if @venta.estado_venta.nil?
        #@venta.errors.add :base, "La venta no se puede actualizar"
        #format.html { render :edit }
        #format.json { render json: @venta.errors, status: :unprocessable_entity }
        #exit
      #end
      ###### Agregar Basicos #####
      #basicos = Array.new
      #if !params[:venta][:basico].nil?
          #params[:venta][:basico].each do | basico |
#            
              #@venta.errors.add :nombre_cliente, "HOLA"
              #basicos.push(:id => basico['id'], :cantidad => basico['cantidad'])
          #end
      #end
#
      #i = 0
      #@venta.basico = Array.new
      #@venta.detalle = Array.new
#
      #@venta.precio_total = 0;
#      
      #basicos.each do | basico |
        #basico_nuevo = Basico.find(basico[:id])
        #@venta.errors.add :comentario_perdida, basico_nuevo.inspect
        #@venta.basico.push basico_nuevo
        #@venta.detalle[i].cantidad = basico[:cantidad]
        #@venta.precio_total += basico_nuevo.precio.to_i * basico[:cantidad].to_i
        #i = i + 1
      #end
      ###### Agregar Basicos #####
      #if @venta.update(venta_params)
        #format.html { redirect_to @venta, notice: 'Venta was successfully updated.' }
        #format.json { render :show, status: :ok, location: @venta }
      #else
        #format.html { render :edit }
        #format.json { render json: @venta.errors, status: :unprocessable_entity }
      #end
    #end
  #end

  # DELETE /venta/1
  # DELETE /venta/1.json
  def destroy
    #@venta.destroy
    mensaje = "Ha ocurrido un error al cancelar la venta."
    if @venta.estado_venta != Venta::ENTREGADA
        mensaje = "Venta cancelada correctamente."
        @venta.estado_venta = Venta::CANCELADA
        @venta.save
    end
    respond_to do |format|
      #format.html { redirect_to venta_url, notice: 'Venta was successfully destroyed.' }
      format.html { redirect_to '/venta', notice: mensaje }
      format.json { head :no_content }
    end
  end

  def preparar
  end

  def cambiar_estado
    #@venta.destroy
    #
    #@venta.estado_venta = nil
    #@venta.save
    #id = params[:id]
    #@venta = 
    estado_actual = @venta.estado_venta.to_i
    estado_nuevo = params[:estado_nuevo].to_i
    mensaje = "No se pudo cambiar el estado de la venta." + estado_actual.to_s
    if estado_nuevo.in?(Venta.estados.values) and estado_actual < estado_nuevo
      @venta.estado_venta = estado_nuevo
      @venta.save
      mensaje = "Estado cambiado correctamente."
      if estado_nuevo == Venta.estados['ENTREGADA']
        mensaje = "Venta entregada correctamente."
      end
    end

    respond_to do |format|
      #format.html { redirect_to '/venta', notice: mensaje}
      format.html { redirect_to '/venta'}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venta
      @venta = Venta.find(params[:id])
    end

app/helpers/venta_helper.rb
module VentaHelper
	def obtener_label_venta estado_venta
        estado_venta = estado_venta.to_i
		if estado_venta == Venta::CANCELADA
        	'<span class="label label-danger">Cancelada</span>'.html_safe
                    
        elsif estado_venta == Venta::EMITIDA
            '<span class="label label-warning">Emitida</span>'.html_safe
    
        elsif estado_venta == Venta::PREPARANDO
            '<span class="label label-warning">Preparando</span>'.html_safe
    
        elsif estado_venta == Venta::FINALIZADA
	    	'<span class="label label-success">Finalizada</span>'.html_safe

        elsif estado_venta == Venta::ENTREGADA
            '<span class="label label-primary">Entregada</span>'.html_safe

	    end
	end
end

app/views/venta/_form.html.erb
<%= page_title "Nueva Venta" %>
<%= form_for(@venta) do |f| %>
  <% elemento = @venta %>
  <% if elemento.errors.any? %>
    <div class="alert alert-warning alert-dismissable">
      <i class="fa fa-warning"></i>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <!-- <i class="fa fa-warning text-yellow"> -->
      <b>Hay errores con los datos que ingreso:</b>
      <ul>
      <% elemento.errors.each do |key, message| %>
        <li>
          <% if key != :general %>
            <%= key.capitalize.to_s.gsub( '_', ' ' ) %> 
          <% end %>
          <%= message %>
        </li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre_cliente %><br>
    <%= f.text_field :nombre_cliente %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <div class="box-header">
      <h3 class="box-title">Productos Basicos</h3>
  </div>
  <% if @diferencia_basicos.any? %>
      <div class="form-group" id="div_select_basico">
          <label for="input_enventa" class="col-sm-2 control-label">Añadir productos básicos</label>
          <div class="col-sm-2">
              <select id="select_basico" class="form-control">
              
                  <% @diferencia_basicos.each do | basico | %>
                    <% if !basico.id.nil? %>
                      <%= ('<option value="' + basico.tipo + '_' + basico.id.to_s + '">' + basico.nombre_producto.capitalize + '</option>').html_safe %>
                    <% end %>
                  <% end %>
              </select>
          </div>
          <div class="col-sm-2">
              <a href="#" id="agregar">Agregar</a>
          </div>
      </div>
  <% end %>

  <%= f.fields_for :basicos do |builder|  %>
      <table class="table table-hover" id="tabla_basicos">
          <tr>
              <th>Nombre</th>
              <th>Cantidad</th>
              <th>Comentario</th>
              <th>Eliminar</th>
          </tr>
          <% if @venta.basico.any? %>
              <% i = 0 %>
              <% @venta.basico.each do | basico | %>
                <% if !basico.nil? %>
                  <tr>
                      <td><%= basico.nombre_producto %></td>
                      <td><input type="text" name="venta[basico][][cantidad]" value="<%= @venta.detalle[i].cantidad        %>"></td>
                      <td><input type="text" name="venta[basico][][comentario]" value="<%= @venta.detalle[i].comentario        %>"></td>
                      <td><a href="#" class="eliminar">Eliminar</a></td>
                  </tr>
                  <% i = i + 1 %>
                <% end %>
              <% end %>
              <% @venta.compuesto.each do | basico | %>
                  <tr>
                      <td><input type="hidden" name="venta[basico][][id]" value="compuesto_<%= basico.id %>">compuesto_<%= basico.id %></td>
                      <td><%= basico.nombre_producto %></td>
                      <td><input type="text" name="venta[basico][][cantidad]" value="<%= @venta.detalle[i].cantidad        %>"></td>
                      <td><input type="text" name="venta[basico][][comentario]" value="<%= @venta.detalle[i].comentario        %>"></td>
                      <td><a href="#" class="eliminar">Eliminar</a></td>
                  </tr>
                  <% i = i + 1 %>
              <% end %>
          <% end %>
      </table>
  <% end %>
<% end %>

<script type="text/javascript">
    $(function(){
        $('#tabla_basicos').delegate('.eliminar', 'click', function(){
            // Agrego el producto a la lista elegible
            var select = $('#select_basico');
            var valor_seleccionado = $(this).closest('input').val();
            if( select.find('option[value='+ valor_seleccionado +']').length == 0){
                var eliminado        = $(this).closest('tr');
                var eliminado_nombre = eliminado.find('td:nth-child(2)');
                var eliminado_value  = eliminado.find('td:nth-child(1)');
                select.append( new Option(eliminado_nombre.text(),eliminado_value.text()) );
            }

            $(this).closest('tr').remove();
            //$('#agregar').show();
            //$('#select_basico').show();
            $('#div_select_basico').show();
        });
        $('#agregar').on('click', function(){
         var row = '<tr>';
            row += '<input type="hidden" name="venta[basico][][id]" value ="'+$('#select_basico').val()+'">';
            row += '<td>' + $('#select_basico :selected').text() + '</td>';
            row += '<td><input type="text" name="venta[basico][][cantidad]" value="1"></td>';
            row += '<td><input type="text" name="venta[basico][][comentario]" value=""></td>';
            row += '<td><a href="#" class="eliminar">Eliminar</a></td>';
            row += '</tr>';
            $('#tabla_basicos tr:last').after(row);

            // Remuevo el producto de la lista elegible
            $('#select_basico :selected').remove();
            if($('#select_basico option').length == 0){
                //$('#agregar').hide();
                //$('#select_basico').hide();
                $('#div_select_basico').hide();
            }
        });
    });
</script>

app/views/venta/edit.html.erb
<h1>Editing ventum</h1>

<%= render 'form' %>

<%= link_to 'Show', @ventum %> |
<%= link_to 'Back', venta_path %>

app/views/venta/historial.html.erb
<%
    base_url = request.url
    if request.path != '/'
        base_url = base_url.gsub(request.path, '')
    end
%>
<link href="<%= base_url %>/AdminLTE/css/daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css" />
<script type="text/javascript">
  $(function(){
    $('#reservation').daterangepicker( {
        format: 'YYYY-MM-DD',
        maxDate: '<%= Time.now.strftime("%Y-%m-%d") %>',
        singleDatePicker: true,
    } );
  });
</script>
<h2>Ventas
  <a href="<%= url_for new_venta_path %>" class="pull-right">
    <button type="button" class="btn btn-success">Nueva Venta</button>
  </a>
</h3>

<div class="row">
    <div class="col-md-3">
        <div class="form-group">
            <label>Date range:</label>
            <div class="input-group">
                <div class="input-group-addon">
                    <i class="fa fa-calendar"></i>
                </div>
                <input type="text" class="form-control pull-right" id="reservation"/>
            </div><!-- /.input group -->
        </div><!-- /.form group -->
    </div>
</div>


<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre cliente</th>
      <th>Precio total</th>
      <th>Vendedor</th>
      <th>Hora</th>
      <th>Caja</th>
      <th>Estado venta</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @venta.each do |venta| %>
      <% venta.estado_venta = venta.estado_venta.to_i %>
      <tr>
        <td><%= venta.nombre_cliente %></td>
        <td><%= venta.precio_total %></td>
        <td><%= venta.user.email %></td>
        <td><%= venta.fecha_hora %></td>
        <td><%= venta.numero_de_caja %></td>
        <td><%= venta.estado_venta %></td>
        <td>
            <%= obtener_label_venta venta.estado_venta %>
            <% if venta.estado_venta == Venta::FINALIZADA %>
                <%= link_to 'Entregar'.html_safe,
                     controller: 'venta',
                     action: 'cambiar_estado',
                     id: venta.id,
                     estado_nuevo: Venta::ENTREGADA %>
            <% elsif venta.estado_venta != Venta::ENTREGADA%>
                <!--
                <%= link_to '++'.html_safe,
                         controller: 'venta',
                         action: 'cambiar_estado',
                         id: venta.id,
                         estado_nuevo: (venta.estado_venta.to_i + 1).to_s %>-->
            <% end %>
        </td>
        <td><%= link_to 'Detalles', venta %></td>
        <!--<td><%= link_to 'Edit', edit_venta_path(venta) %></td>-->
        <td>
        
            <% if venta.estado_venta.in?([Venta::EMITIDA, Venta::PREPARANDO]) %>
                <%= link_to '<i class="fa fa-times"></i>'.html_safe, venta, method: :delete, data: { confirm: 'Esta seguro?' } %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/venta/index.html.erb
<%
    base_url = request.url
    if request.path != '/'
        base_url = base_url.gsub(request.path, '')
    end
%>
<link href="<%= base_url %>/AdminLTE/css/daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css" />
<script type="text/javascript">
  $(function(){
    $('#reservation').daterangepicker();
  });
</script>
<h2>Ventas
  <a href="<%= url_for new_venta_path %>" class="pull-right">
    <button type="button" class="btn btn-success">Nueva Venta</button>
  </a>
</h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre cliente</th>
      <th>Precio total</th>
      <th>Vendedor</th>
      <th>Hora</th>
      <th>Caja</th>
      <th>Estado venta</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @venta.each do |venta| %>
      <% venta.estado_venta = venta.estado_venta.to_i %>
      <tr>
        <td><%= venta.nombre_cliente %></td>
        <td><%= venta.precio_total %></td>
        <td><%= venta.user.email %></td>
        <td><%= venta.fecha_hora.to_formatted_s(:time) %></td>
        <td><%= venta.numero_de_caja %></td>
        <td><%= venta.estado_venta %></td>
        <td>
            <%= obtener_label_venta venta.estado_venta %>
            <% if venta.estado_venta == Venta::FINALIZADA %>
                <%= link_to 'Entregar'.html_safe,
                     controller: 'venta',
                     action: 'cambiar_estado',
                     id: venta.id,
                     estado_nuevo: Venta::ENTREGADA %>
            <% elsif venta.estado_venta != Venta::ENTREGADA%>
                <!--
                <%= link_to '++'.html_safe,
                         controller: 'venta',
                         action: 'cambiar_estado',
                         id: venta.id,
                         estado_nuevo: (venta.estado_venta.to_i + 1).to_s %>-->
            <% end %>
        </td>
        <td><%= link_to 'Detalles', venta %></td>
        <!--<td><%= link_to 'Edit', edit_venta_path(venta) %></td>-->
        <td>
        
            <% if venta.estado_venta.in?([Venta::EMITIDA, Venta::PREPARANDO]) %>
                <%= link_to '<i class="fa fa-times"></i>'.html_safe, venta, method: :delete, data: { confirm: 'Esta seguro?' } %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/venta/new.html.erb
<%= render 'form' %>

app/views/venta/preparar.html.erb
<% @ventas.each do | venta | %>
	<%= venta.id %>
<% end %>

app/views/venta/show.html.erb
<p>
  <strong>Vendedor:</strong>
  <%= @venta.user.email %>
</p>

<p>
  <strong>Fecha hora:</strong>
  <%= @venta.fecha_hora %>
  <!-- .strftime("%d-%m-%Y %H:%M") -->
</p>

<p>
  <strong>Nombre cliente:</strong>
  <%= @venta.nombre_cliente %>
</p>

<p>
  <strong>Precio total:</strong>
  <%= @venta.precio_total %>
</p>

<p>
  <strong>Comentario perdida:</strong>
  <%= @venta.comentario_perdida %>
</p>

<p>
  <strong>Numero de caja:</strong>
  <%= @venta.numero_de_caja %>
</p>

<p>
  <strong>Estado venta:</strong><%= obtener_label_venta @venta.estado_venta %>
</p>

<p>
  <strong>Tiempo terminado venta:</strong>
  <%= @venta.tiempo_terminado_venta %>
</p>

<!--%= link_to 'Edit', edit_venta_path(@venta) %> |
<%= link_to 'Back', venta_path %>-->

<div class="box-header">
  <h3 class="box-title">Productos Basicos</h3>
</div>
<table class="table table-hover" id="tabla_basicos">
    <tr>
        <th>Nombre</th>
        <th>Cantidad</th>
        <th>Precio</th>
        <th>Total</th>
        <th>Comentario</th>
    </tr>
    <% if @venta.detalle.any? %>
        <% i_basicos = 0 %>
        <% i_compuestos = 0 %>
        <% i = 0 %>
        <% @venta.detalle.each do | detalle | %>
            <tr>
                <td>
                    <% if !detalle.basico_id.nil? %>
                        <%= @venta.basico[ i_basicos ].nombre_producto %>
                        <% i_basicos = i_basicos + 1 %>
                    <% elsif !detalle.compuesto_id.nil? %>
                        <%= @venta.compuesto[ i_compuestos ].nombre_producto %>
                        <% i_compuestos = i_compuestos + 1 %>
                    <% end %>
                </td>
                <td><%= @venta.detalle[i].cantidad %></td>
                <td><%= @venta.detalle[i].precio / @venta.detalle[i].cantidad %></td>
                <td><%= @venta.detalle[i].precio %></td>
                <td><%= @venta.detalle[i].comentario %></td>
            </tr>
            <% i = i + 1 %>
        <% end %>
    <% end %>
</table>