config/routes.rb
Rails.application.routes.draw do

  resources :merma_lotes

  resources :merma_vencimientos

  resources :detalle_entrega_insumos

  resources :detalles_basicos

  resources :create_detalles_basicos

  resources :proveedors

  get 'recepcion_materiales/insumos'

  get 'recepcion_materiales/ingredientes'

  resources :merma_ingredientes

  resources :merma_insumos

  match "/404", :to => "errors#not_found", via: 'get'
  match "/422", :to => "errors#unacceptable", via: 'get'
  match "/500", :to => "errors#internal_error", via: 'get'
  match "/acceso_denegado", :to => "errors#acceso_denegado", via: 'get'
  
  post 'users/crear' => 'user#crear'
  get '/usuarios' => 'user#index'

  get 'preparar' => 'preparar#index'
  get 'preparar_pruebas' => 'preparar#pruebas'
  get 'preparar/cambiar_estado/:id_venta/:tipo_producto/:id_producto' => 'preparar#cambiar_estado'

  resources :lotes

  resources :insumos

  resources :merma_materials and resources :merma_material

  get 'mermas/ingresar_merma'

  resources :detalles

  get 'venta/historial' => 'venta#historial'
  get 'venta/:id/cambiar_estado/:estado_nuevo' => 'venta#cambiar_estado'
  resources :venta do
    get 'index_path'
  end

  resources :ingredientes and resources :ingrediente

  devise_for :users
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/users/sign_up' => 'devise/registrations#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  resources :users, :controller => "user"

  root 'basicos#index'
  resources :alerta_obsolescencia

  resources :compuestos

  resources :basicos

  post ':controller(/:action(/:id(.:format)))'
  get ':controller(/:action(/:id(.:format)))'

end

app/models/create_detalles_basico.rb
class CreateDetallesBasico < ActiveRecord::Base
end

app/controllers/create_detalles_basicos_controller.rb
class CreateDetallesBasicosController < ApplicationController
  before_action :set_create_detalles_basico, only: [:show, :edit, :update, :destroy]

  # GET /create_detalles_basicos
  # GET /create_detalles_basicos.json
  def index
    @create_detalles_basicos = CreateDetallesBasico.all
  end

  # GET /create_detalles_basicos/1
  # GET /create_detalles_basicos/1.json
  def show
  end

  # GET /create_detalles_basicos/new
  def new
    @create_detalles_basico = CreateDetallesBasico.new
  end

  # GET /create_detalles_basicos/1/edit
  def edit
  end

  # POST /create_detalles_basicos
  # POST /create_detalles_basicos.json
  def create
    @create_detalles_basico = CreateDetallesBasico.new(create_detalles_basico_params)

    respond_to do |format|
      if @create_detalles_basico.save
        format.html { redirect_to @create_detalles_basico, notice: 'Create detalles basico was successfully created.' }
        format.json { render :show, status: :created, location: @create_detalles_basico }
      else
        format.html { render :new }
        format.json { render json: @create_detalles_basico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /create_detalles_basicos/1
  # PATCH/PUT /create_detalles_basicos/1.json
  def update
    respond_to do |format|
      if @create_detalles_basico.update(create_detalles_basico_params)
        format.html { redirect_to @create_detalles_basico, notice: 'Create detalles basico was successfully updated.' }
        format.json { render :show, status: :ok, location: @create_detalles_basico }
      else
        format.html { render :edit }
        format.json { render json: @create_detalles_basico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /create_detalles_basicos/1
  # DELETE /create_detalles_basicos/1.json
  def destroy
    @create_detalles_basico.destroy
    respond_to do |format|
      format.html { redirect_to create_detalles_basicos_url, notice: 'Create detalles basico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_create_detalles_basico
      @create_detalles_basico = CreateDetallesBasico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def create_detalles_basico_params
      params.require(:create_detalles_basico).permit(:basico_id, :ingrediente_id, :cantidad)
    end
end

app/helpers/create_detalles_basicos_helper.rb
module CreateDetallesBasicosHelper
end

app/views/create_detalles_basicos/_form.html.erb
<%= simple_form_for(@create_detalles_basico) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :basico_id %>
    <%= f.input :ingrediente_id %>
    <%= f.input :cantidad %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/create_detalles_basicos/edit.html.erb
<h1>Editing create_detalles_basico</h1>

<%= render 'form' %>

<%= link_to 'Show', @create_detalles_basico %> |
<%= link_to 'Back', create_detalles_basicos_path %>

app/views/create_detalles_basicos/index.html.erb
<h1>Listing create_detalles_basicos</h1>

<table>
  <thead>
    <tr>
      <th>Basico</th>
      <th>Ingrediente</th>
      <th>Cantidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @create_detalles_basicos.each do |create_detalles_basico| %>
      <tr>
        <td><%= create_detalles_basico.basico_id %></td>
        <td><%= create_detalles_basico.ingrediente_id %></td>
        <td><%= create_detalles_basico.cantidad %></td>
        <td><%= link_to 'Show', create_detalles_basico %></td>
        <td><%= link_to 'Edit', edit_create_detalles_basico_path(create_detalles_basico) %></td>
        <td><%= link_to 'Destroy', create_detalles_basico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Create detalles basico', new_create_detalles_basico_path %>

app/views/create_detalles_basicos/new.html.erb
<h1>New create_detalles_basico</h1>

<%= render 'form' %>

<%= link_to 'Back', create_detalles_basicos_path %>

app/views/create_detalles_basicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Basico:</strong>
  <%= @create_detalles_basico.basico_id %>
</p>

<p>
  <strong>Ingrediente:</strong>
  <%= @create_detalles_basico.ingrediente_id %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @create_detalles_basico.cantidad %>
</p>

<%= link_to 'Edit', edit_create_detalles_basico_path(@create_detalles_basico) %> |
<%= link_to 'Back', create_detalles_basicos_path %>