config/routes.rb
Rails.application.routes.draw do

  resources :merma_lotes

  resources :merma_vencimientos

  resources :detalle_entrega_insumos

  resources :detalles_basicos

  resources :create_detalles_basicos

  resources :proveedors

  get 'recepcion_materiales/insumos'

  get 'recepcion_materiales/ingredientes'

  resources :merma_ingredientes

  resources :merma_insumos

  match "/404", :to => "errors#not_found", via: 'get'
  match "/422", :to => "errors#unacceptable", via: 'get'
  match "/500", :to => "errors#internal_error", via: 'get'
  match "/acceso_denegado", :to => "errors#acceso_denegado", via: 'get'
  
  post 'users/crear' => 'user#crear'
  get '/usuarios' => 'user#index'

  get 'preparar' => 'preparar#index'
  get 'preparar_pruebas' => 'preparar#pruebas'
  get 'preparar/cambiar_estado/:id_venta/:tipo_producto/:id_producto' => 'preparar#cambiar_estado'

  resources :lotes

  resources :insumos

  resources :merma_materials and resources :merma_material

  get 'mermas/ingresar_merma'

  resources :detalles

  get 'venta/historial' => 'venta#historial'
  get 'venta/:id/cambiar_estado/:estado_nuevo' => 'venta#cambiar_estado'
  resources :venta do
    get 'index_path'
  end

  resources :ingredientes and resources :ingrediente

  devise_for :users
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/users/sign_up' => 'devise/registrations#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  resources :users, :controller => "user"

  root 'basicos#index'
  resources :alerta_obsolescencia

  resources :compuestos

  resources :basicos

  post ':controller(/:action(/:id(.:format)))'
  get ':controller(/:action(/:id(.:format)))'

end

app/models/insumo.rb
class Insumo < ActiveRecord::Base
	has_many :merma_insumos
end

app/controllers/insumos_controller.rb
class InsumosController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_insumo, only: [:show, :edit, :update, :destroy]

  
  # GET /insumos
  # GET /insumos.json
  def index
    @insumos = Insumo.all
  end

  # GET /insumos/1
  # GET /insumos/1.json
  def show
  end

  # GET /insumos/new
  def new
    @insumo = Insumo.new
  end

  # GET /insumos/1/edit
  def edit
  end

  # POST /insumos
  # POST /insumos.json
  def create
    @edit = false
    @insumo = Insumo.new(insumo_params)

    respond_to do |format|
      if @insumo.save
        format.html { redirect_to '/insumos', notice: 'Insumo creado correctamente.' }
        format.json { render :show, status: :created, location: @insumo }
      else
        format.html { render :new }
        format.json { render json: @insumo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insumos/1
  # PATCH/PUT /insumos/1.json
  def update
    @edit = true
    respond_to do |format|
      if @insumo.update(insumo_params)
        format.html { redirect_to '/insumos', notice: 'Insumo editado correctamente.' }
        format.json { render :show, status: :ok, location: @insumo }
      else
        format.html { render :edit }
        format.json { render json: @insumo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insumos/1
  # DELETE /insumos/1.json
  def destroy
    @insumo.destroy
    respond_to do |format|
      format.html { redirect_to insumos_url, notice: 'Insumo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insumo
      @insumo = Insumo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def insumo_params
      params.require(:insumo).permit(:tipo_insumo, :nombre_insumo, :categoria_insumo, :stock_actual, :stock_critico, :stock_ideal)
    end
end

app/helpers/insumos_helper.rb
module InsumosHelper
end

app/views/insumos/_form.html.erb
<%= simple_form_for(@insumo) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <% tiposInsumo = {'Envase' => 'Envase', 'Envoltorio' => 'Envoltorio', 'Higiene' => 'Higiene'} %>
    <%= f.input :tipo_insumo, collection: tiposInsumo, prompt: "Eliga un tipo...", disabled: @edit %>
    <%= f.input :nombre_insumo, disabled: @edit %>
    <!--%= f.input :categoria_insumo %-->
    <%= f.input :stock_actual, disabled: @edit %>
    <%= f.input :stock_critico %>
    <%= f.input :stock_ideal %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/insumos/edit.html.erb
<%= page_title "Modificar insumo" %>

<% @edit = true %>

<%= render 'form' %>

<%= link_to 'Back', insumos_path %>

app/views/insumos/index.html.erb
<%= page_title "Insumos" %>
<a href="<%= url_for new_insumo_path %>" class="pull-right"><button type="button" class="btn btn-success">Añadir Insumo</button></a>
<div class="row">
    <div class="col-xs-12">
        <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <tr>
                <th>Tipo insumo</th>
                <th>Nombre insumo</th>
                <th>Categoria insumo</th>
                <th>Stock actual</th>
                <th>Stock critico</th>
                <th>Stock ideal</th>
                <th colspan="2"></th>
            </tr>

            <% @insumos.each do |insumo| %>
              <tr>
                <td><%= insumo.tipo_insumo %></td>
                <td><%= insumo.nombre_insumo %></td>
                <td><%= insumo.categoria_insumo %></td>
                <td><%= insumo.stock_actual %></td>
                <td><%= insumo.stock_critico %></td>
                <td><%= insumo.stock_ideal %></td>
                <td><%= link_to 'Editar', edit_insumo_path(insumo) %></td>
              </tr>
            <% end %>
          </table>
        </div><!-- /.box-body -->
    </div>
</div>

app/views/insumos/new.html.erb
<%= page_title "Nuevo Insumo" %>
<%= render 'form' %>

<%= link_to 'Back', insumos_path %>

app/views/insumos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo insumo:</strong>
  <%= @insumo.tipo_insumo %>
</p>

<p>
  <strong>Nombre insumo:</strong>
  <%= @insumo.nombre_insumo %>
</p>

<p>
  <strong>Categoria insumo:</strong>
  <%= @insumo.categoria_insumo %>
</p>

<p>
  <strong>Stock actual:</strong>
  <%= @insumo.stock_actual %>
</p>

<p>
  <strong>Stock critico:</strong>
  <%= @insumo.stock_critico %>
</p>

<p>
  <strong>Stock ideal:</strong>
  <%= @insumo.stock_ideal %>
</p>

<%= link_to 'Edit', edit_insumo_path(@insumo) %> |
<%= link_to 'Back', insumos_path %>