config/routes.rb
Rails.application.routes.draw do

  resources :merma_lotes

  resources :merma_vencimientos

  resources :detalle_entrega_insumos

  resources :detalles_basicos

  resources :create_detalles_basicos

  resources :proveedors

  get 'recepcion_materiales/insumos'

  get 'recepcion_materiales/ingredientes'

  resources :merma_ingredientes

  resources :merma_insumos

  match "/404", :to => "errors#not_found", via: 'get'
  match "/422", :to => "errors#unacceptable", via: 'get'
  match "/500", :to => "errors#internal_error", via: 'get'
  match "/acceso_denegado", :to => "errors#acceso_denegado", via: 'get'
  
  post 'users/crear' => 'user#crear'
  get '/usuarios' => 'user#index'

  get 'preparar' => 'preparar#index'
  get 'preparar_pruebas' => 'preparar#pruebas'
  get 'preparar/cambiar_estado/:id_venta/:tipo_producto/:id_producto' => 'preparar#cambiar_estado'

  resources :lotes

  resources :insumos

  resources :merma_materials and resources :merma_material

  get 'mermas/ingresar_merma'

  resources :detalles

  get 'venta/historial' => 'venta#historial'
  get 'venta/:id/cambiar_estado/:estado_nuevo' => 'venta#cambiar_estado'
  resources :venta do
    get 'index_path'
  end

  resources :ingredientes and resources :ingrediente

  devise_for :users
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/users/sign_up' => 'devise/registrations#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  resources :users, :controller => "user"

  root 'basicos#index'
  resources :alerta_obsolescencia

  resources :compuestos

  resources :basicos

  post ':controller(/:action(/:id(.:format)))'
  get ':controller(/:action(/:id(.:format)))'

end

app/models/merma_ingrediente.rb
class MermaIngrediente < ActiveRecord::Base
  belongs_to :ingrediente
  validates :cantidad, :numericality => { :greater_than_or_equal_to => 0}
  validates :cantidad, presence: true
  validate :fecha_debe_ser_menor_a_hoy
  validate :ingrediente_debe_existir
  
  def fecha_debe_ser_menor_a_hoy
    if fecha_merma.present? && fecha_merma > Date.today
      errors.add(:general, "La fecha no puede ser en el futuro")
    end
  end

  def ingrediente_debe_existir
    if Ingrediente.where(id: ingrediente_id).empty?
      errors.add(:general, "El ingrediente seleccionado no existe")
    end
  end
end

app/controllers/merma_ingredientes_controller.rb
class MermaIngredientesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_merma_ingrediente, only: [:show, :edit, :update, :destroy]

  # GET /merma_ingredientes
  # GET /merma_ingredientes.json
  def index
    @merma_ingredientes = MermaIngrediente.all
  end

  # GET /merma_ingredientes/1
  # GET /merma_ingredientes/1.json
  def show
  end

  # GET /merma_ingredientes/new
  def new
    @merma_ingrediente = MermaIngrediente.new
    @merma_ingrediente.cantidad = 0
  end

  # GET /merma_ingredientes/1/edit
  def edit
  end

  # POST /merma_ingredientes
  # POST /merma_ingredientes.json
  def create
    @merma_ingrediente = MermaIngrediente.new(merma_ingrediente_params)

    respond_to do |format|
      if @merma_ingrediente.save
        format.html { redirect_to '/merma_ingredientes', notice: 'Merma agregada correctamente.' }
        format.json { render :show, status: :created, location: @merma_ingrediente }
      else
        format.html { render :new }
        format.json { render json: @merma_ingrediente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /merma_ingredientes/1
  # PATCH/PUT /merma_ingredientes/1.json
  def update
    respond_to do |format|
      if @merma_ingrediente.update(merma_ingrediente_params)
        format.html { redirect_to @merma_ingrediente, notice: 'Merma ingrediente was successfully updated.' }
        format.json { render :show, status: :ok, location: @merma_ingrediente }
      else
        format.html { render :edit }
        format.json { render json: @merma_ingrediente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merma_ingredientes/1
  # DELETE /merma_ingredientes/1.json
  def destroy
    @merma_ingrediente.destroy
    respond_to do |format|
      format.html { redirect_to merma_ingredientes_url, notice: 'Merma ingrediente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merma_ingrediente
      @merma_ingrediente = MermaIngrediente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def merma_ingrediente_params
      params.require(:merma_ingrediente).permit(:cantidad, :fecha_merma, :comentario_merma, :ingrediente_id)
    end
end

app/helpers/merma_ingredientes_helper.rb
module MermaIngredientesHelper
end

app/views/merma_ingredientes/_form.html.erb
<%= simple_form_for(@merma_ingrediente , :html => {:class => "form-horizontal"}) do |f| %>
  <% elemento = @merma_ingrediente %>
  <% if elemento.errors.any? %>
    <div class="alert alert-warning alert-dismissable">
      <i class="fa fa-warning"></i>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <!-- <i class="fa fa-warning text-yellow"> -->
      <b>Hay errores con los datos que ingreso:</b>
      <ul>
      <% elemento.errors.each do |key, message| %>
        <li>
          <% if key != :general %>
            <%= key.capitalize.to_s.gsub( '_', ' ' ) %> 
          <% end %>
          <%= message %>
        </li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <div class="form-group" class="field">
        <div class="col-sm-2">
          <%= f.input :cantidad  %>
        </div>
    </div>

    <div class="form-group" class="field">
        <div class="col-sm-2">
          <%= f.input :fecha_merma %>
      </div>
    </div>

    <div class="form-group" class="field">
        <div class="col-sm-2">
          <%= f.input :comentario_merma %>
      </div>
    </div>

    <div class="form-group" class="field">
      <div class="col-sm-2">
        <%= f.association :ingrediente, label_method: :nombre, value_method: :id, prompt: "Eliga uno..."%>
      </div>
    </div>
  </div>

  <div class="form-group" class="field">
        <div class="col-sm-offset-2">
            <%= boton_guardar_cancelar((f.submit "Guardar", :class => "btn btn-success"), merma_ingredientes_path) %>
        </div>
    </div>
<% end %>

app/views/merma_ingredientes/edit.html.erb
<h1>Editing merma_ingrediente</h1>

<%= render 'form' %>

<%= link_to 'Show', @merma_ingrediente %> |
<%= link_to 'Back', merma_ingredientes_path %>

app/views/merma_ingredientes/index.html.erb
<%= page_title "Mermas - Ingredientes" %>
<a href="<%= url_for new_merma_ingrediente_path %>" class="pull-right"><button type="button" class="btn btn-success">Añadir Nueva Merma de Ingrediente</button></a>
<div class="row">
    <div class="col-xs-12">
        <div class="box-body table-responsive no-padding">
            <table class="table table-hover">
  <thead>
    <tr>
      <th>Cantidad</th>
      <th>Fecha merma</th>
      <th>Comentario merma</th>
      <th>Ingrediente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @merma_ingredientes.each do |merma_ingrediente| %>
      <tr>
        <td><%= merma_ingrediente.cantidad %></td>
        <td><%= merma_ingrediente.fecha_merma %></td>
        <td><%= merma_ingrediente.comentario_merma %></td>
        <td><%= merma_ingrediente.ingrediente.nombre.capitalize %></td>
        <td><%= link_to 'Editar', edit_merma_ingrediente_path(merma_ingrediente) %></td>
        <td><%= link_to 'Eliminar', merma_ingrediente, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
        </div><!-- /.box-body -->
    </div>
</div>

app/views/merma_ingredientes/new.html.erb
<h1>Nueva Merma de Ingrediente</h1>

<%= render 'form' %>

app/views/merma_ingredientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cantidad:</strong>
  <%= @merma_ingrediente.cantidad %>
</p>

<p>
  <strong>Fecha merma:</strong>
  <%= @merma_ingrediente.fecha_merma %>
</p>

<p>
  <strong>Comentario merma:</strong>
  <%= @merma_ingrediente.comentario_merma %>
</p>

<p>
  <strong>Ingrediente:</strong>
  <%= @merma_ingrediente.ingrediente %>
</p>

<%= link_to 'Edit', edit_merma_ingrediente_path(@merma_ingrediente) %> |
<%= link_to 'Back', merma_ingredientes_path %>